#Intro,System Specifications

In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 23
model		: 49
model name	: AMD EPYC 7B12
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2249.998
cache size	: 512 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid
bugs		: sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass retbleed smt_rsb srso
bogo

In [ ]:
!cat /proc/meminfo

MemTotal:       13290460 kB
MemFree:         7274936 kB
MemAvailable:   12112504 kB
Buffers:          378832 kB
Cached:          4602280 kB
SwapCached:            0 kB
Active:           701844 kB
Inactive:        4966752 kB
Active(anon):       1260 kB
Inactive(anon):   687808 kB
Active(file):     700584 kB
Inactive(file):  4278944 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               280 kB
Writeback:             0 kB
AnonPages:        687520 kB
Mapped:           327404 kB
Shmem:              1576 kB
KReclaimable:     183444 kB
Slab:             226464 kB
SReclaimable:     183444 kB
SUnreclaim:        43020 kB
KernelStack:        5872 kB
PageTables:        10628 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6645228 kB
Committed_AS:    3019304 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       12232 kB
VmallocChunk:    

Installing Libraries

In [ ]:
pip install pandas

In [ ]:
print('Machine Learning')

Machine Learning


To list all files and folders

In [ ]:
!ls


sample_data


#Basic Datatypes--


In [ ]:
type(8)

int

In [ ]:
type("English")

str

variables

In [ ]:
superhero='Ironman'
print(superhero)

Ironman


In [ ]:
hero1,hero2,hero3="Iron man","Captain America","Bat man"
print(hero1)
print(hero2)
print(hero3)

Iron man
Captain America
Bat man


#Input Function-

In [ ]:
number_1=int(input("Enter the first number : "))
number_2=int(input("Enter the second number : "))
sum=number_1+number_2
print(sum)



Enter the first number : 10
Enter the second number : 5
15


In [ ]:
#converting datatype
num=5
print(float(num))

5.0


In [ ]:
#complex number
c = 1 + 3j
print(c)
type(c)

(1+3j)


complex

In [ ]:
#Boolean
a=True
print(a)


b= 7<3
print(b)
type(b)

True
False


bool

Strings-

In [ ]:
print("Hello "*5)

Hello Hello Hello Hello Hello 


Slicing in strings-

In [ ]:
my_string="Programming"
print(my_string[1:5])

rogr


In [ ]:
#step
print(my_string[0:10:2])


Pormi


#Immutable objects:
  1.int
  2.float
  3.string
  4.bool
  5.tuple

Mutable objects:
  1.List
  2.Set
  3.Dictionary

In [ ]:
#list should be included in square bracket[]
my_list=[1,2,3,4,5]
print(my_list)
type(my_list)
#Lists can have multiple datatypes..
#Lists are mutable
my_list.append(6)
print(my_list)
#print elements using index
print(my_list[0])
#allows duplicate values..
print(len(my_list))
#initiating an empty list..
list_2=[]
print(list_2)
list_2.append(5);
print(list_2)
del list_2[0]
print(list_2)


[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
1
6
[]
[5]
[]


Tuple


In [ ]:
tuple_1=(2,3,4)
print(tuple_1)
type(tuple_1)
#allows multiple datatypes...

(2, 3, 4)


tuple

In [ ]:
#Converting list to a tuple:
my_list=[3,4,5,6]
print(my_list)
my_tuple=tuple(my_list)
print(my_tuple)
#we cannot change the contents of any tuple because they are immutable..
print(len(my_tuple))

[3, 4, 5, 6]
(3, 4, 5, 6)
4


Set

In [ ]:
#curly brackets{}
my_set={1,2,3,4,5}
print(my_set)
type(my_set)
#set doesnot allow duplicate values..

{1, 2, 3, 4, 5}


set

Dictionary

Key-value pair

In [ ]:
 my_dictionary={'name':'David','age':30,'country':'India'}
 print(my_dictionary)
 type(my_dictionary)
 print(my_dictionary['name'])
 print(my_dictionary['age'])
 print(my_dictionary['country'])
 #dosent allow duplicate values..

{'name': 'David', 'age': 30, 'country': 'India'}
David
30
India


#Operators in python-
  1.Assignment
  2.arthematic
  3.logical
  4.comparision
  5.identity
  6.membership

In [ ]:
num1=10
num2=20
sum=num1+num2
print('The sum of two numbers is',sum)
#comparision:and,or,is,not
#membership:in,not in
a=5
b=10
c=[1,2,3,4,5]
print(a in c)
print(b in c)
print(a not in c)

The sum of two numbers is 30
True
False
False


#If else statements:

In [ ]:
a=30
b=50
if(a>b):
  print('A is greater')
else:
  print('B is Greater..')

B is Greater..


In [ ]:
a=int(input('Enter the first number :'))
b=int(input('Enter the second number :'))
if(a>b):
  print(a,'is greater')
else:
  print(b,'is Greater..')


Enter the first number :500
Enter the second number :1000
1000 is Greater..


In [ ]:
a=15
b=55
c=30
if(a>b):
  if(a>c):
    print(a,'is greater')
  else:
    print(c,'is greater')
else:
  if(b>c):
    print(b,'is greater')
  else:
    print(c,'is greater')


55 is greater


#LOOPS



For Loop:

In [ ]:

for i in range(5):
  laptop_price = int(input('Enter the price of laptop '))



Enter the price of laptop 10
Enter the price of laptop 20
Enter the price of laptop 30
Enter the price of laptop 40
Enter the price of laptop 50


In [ ]:
numbers=[50,100,150,200]
for i in numbers:
  print(i)

50
100
150
200


While loop:

In [ ]:
i = 0
while i<10:
  print(i)
  i+=1


0
1
2
3
4
5
6
7
8
9


#Functions:--

Factorial of a number

Normal:

In [ ]:
number = int(input('Enter a number to find its factorial: '))
factorial=1

if number==0:
  print('The factorial of number is 0')
else:
  for i in range(1,number+1):
    factorial=factorial*i
  print('The factorial of given number is:',factorial)


Enter a number to find its factorial: 10
The factorial of given number is: 3628800


Using function

In [ ]:
def factorial_value(num):
  factorial=1
  if num == 0 :
    return 1;
  else:
    for i in range(1,num+1):
      factorial= factorial*i
    return factorial





In [ ]:
print('The factorial of number 5 is',factorial_value(5));

The factorial of number 5 is 120


#NumPy


-Allows several mathematecial operations, Faster operations

In [ ]:
import numpy as np


List vs Numpy- Time Taken

In [ ]:
from time import process_time

Time taken by list


In [ ]:
python_list=[i for i in range(10000)]

start_time = process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)


0.00041431100000011156


time taken by numpy array

In [ ]:
np_array=np.array([i for i in range(10000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)

0.0001021300000001446


Numpy array

In [ ]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

2d array

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
#array of 1s
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


Identity matrix

In [ ]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#creating array with random numbers:
b= np.random.random((3,4))
print(b)

[[0.8551577  0.54223913 0.93319001 0.76652798]
 [0.6051584  0.469595   0.21956736 0.32992245]
 [0.76878277 0.5917339  0.56837511 0.87425899]]


In [ ]:
# generating array with random integers:
c = np.random.randint(10,100,(5,5))
print(c)

[[41 97 25 64 59]
 [55 20 45 42 85]
 [88 93 66 38 26]
 [25 27 47 48 30]
 [83 98 63 11 76]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)

[[76 12 48 69 35]
 [14 55 32 38 46]
 [70 47 11 31 51]
 [12 54 28 46 68]
 [86 39 46 45 53]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# number of elements in an array
print(c.size)

25


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical Operations on nparray:


In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[2 6 7]
 [0 5 5]
 [3 0 0]]
[[19 18 19]
 [10 13 17]
 [16 10 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[21 24 26]
 [10 18 22]
 [19 10 10]]
[[-17 -12 -12]
 [-10  -8 -12]
 [-13 -10 -10]]
[[ 38 108 133]
 [  0  65  85]
 [ 48   0   0]]
[[0.10526316 0.33333333 0.36842105]
 [0.         0.38461538 0.29411765]
 [0.1875     0.         0.        ]]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [ ]:
print(a)
print(b)

[[4 9 1]
 [5 0 0]
 [2 6 4]]
[[15 18 17]
 [17 16 12]
 [18 10 18]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 27 18]
 [22 16 12]
 [20 16 22]]
[[-11  -9 -16]
 [-12 -16 -12]
 [-16  -4 -14]]
[[ 60 162  17]
 [ 85   0   0]
 [ 36  60  72]]
[[0.26666667 0.5        0.05882353]
 [0.29411765 0.         0.        ]
 [0.11111111 0.6        0.22222222]]


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 5 2]
 [4 7 4]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 4]
 [5 7]
 [2 4]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 7 5]
 [0 3 5]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[0 0]
 [7 3]
 [5 5]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 7 4]
 [5 3 5]]
(2, 3)


In [ ]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 7]
 [4 5]
 [3 5]]
(3, 2)


#Data Collection


* Kaggle
* uci machine learning repo
* Google dataset search








In [ ]:
 import pandas as pd

In [ ]:
#loading a dataset to a pandas dataframe:
dataset = pd. read_csv('/content/boston.csv')

In [ ]:
dataset.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2


In [ ]:
#installing the kaggle library
!pip install kaggle

Upload Your kaggle.json file

In [ ]:
#configuring the path of kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

Importing the Earthquake dataset

In [ ]:
# API to fetch the dataset from Kaggle
!kaggle competitions download -c LANL-Earthquake-Prediction

403 Client Error: Forbidden for url: https://www.kaggle.com/api/v1/competitions/data/download-all/LANL-Earthquake-Prediction
